### PR TITLE
docs(README): add import example

### LINKED ISSUE #35: docs(README): add import example
As a user of the library, 
I would like the readme to list the import statement of dismock, 
so I can easily figure out the v2 import path. 

I believe this should either:

1. Be added to the top of the examples like this one:
image

2. or be listed under a dedicated header in the readme file, something like this example: https://github.com/mikespook/gorbac#preparing

I am happy to raise a PR for either of these options if desired :)

### PR DESCRIPTION
**Pull request by danstis**
fixes #35

### CODE REVIEW

**Review by mavolin — CHANGES_REQUESTED** [review]
While dismock is currently only has a single package, that might change if #28 ever gets implemented. Therefore, I don't think this is the way we should solve this.
If the version number in the path is the only concern, we could adapt this to:
```markdown
#### `go get` the Module

```bash
go get github.com/mavolin/dismock/v2
​```
```

Otherwise, I would suggest to go with your first suggestion in #35 and add proper import statements to all examples. Note that if you opt to do this, you should add all imports, i.e. arikawa imports etc. as well, not just the dismock import, as this might cause confusion, otherwise.

**Comment by danstis** [comment]
Is there any concern with adding both: the go get statement as well as full imports on every example?
I'll update the PR to match.

**Comment by mavolin** [comment]
No that's fine with me.

**Comment by mavolin** [comment]
@danstis Hey, what's the status on the changes?

**Comment by danstis** [comment]
> @danstis Hey, what's the status on the changes?

I started by going through the examples and noticed most didn't compile, so I took a note to fix them as well. But then I got a bit carried away with work tasks (and some playing of games! :) ). I'll get back onto this one.

**Comment by danstis** [comment]
Ok, added the full examples and the Go Get command. 
Also the examples now work, should we potentially add an examples folder with working examples in it?

**Review by mavolin — APPROVED** [review]
LGTM. Thank you for adding this.

**Comment by mavolin** [comment]
Idk why, but GitHub did not mark this PR as merged even though it is. Closing this manually as the changes are in merged into v2.

**Pull request closed without merging**
